apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: p8ptil5vx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: p8ptil5vx-nodejs 
  name: p8ptil5vx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: p8ptil5vx-nodejs 
